### ISSUE TITLE
scalacheck property testing starting to flake

### ISSUE THREAD

**Issue by erikerlandson** [erikerlandson/coulomb#133]
Starting with #132, getting some transient property testing flakes in scalacheck.  Deviations in the last digit (ULP).  ~Looks like it is specifically in on the JS side~

**Comment by erikerlandson** [comment]
These are appearing on both the jvm and js side

**Comment by erikerlandson** [comment]
example test failure
```
failing seed for monoid.associative is vorU88H7MD18Erf_gfzrqPcGkrp0HvPyGIqLCmjAsBP=
==> X coulomb.cats.CatsSuite.MonoidTest: monoid.associative  0.06s munit.FailException: /home/runner/work/coulomb/coulomb/coulomb-tests/shared/src/test/scala/coulomb/cats/CatsSuite.scala:52
51:  checkAll("CommutativeMonadTest", CommutativeMonadTests[Quantity[*, KilometersPerSecond]].commutativeMonad[Int, Int, Int])
52:  checkAll("MonoidTest", MonoidTests[Quantity[Double, KilometersPerSecond]].monoid)
53:}

Failing seed: ytunghLfd8B-AeCV6CMGGxRGXIKF6r1EzuSxppfheTP=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "ytunghLfd8B-AeCV6CMGGxRGXIKF6r1EzuSxppfheTP="

Falsified after 18 passed tests.
> Labels of failing property: 
Expected: Quantity(1.2979896686839215E124)
Received: Quantity(1.2979896686839217E124)
> ARG_0: Quantity(3.294119796979299E108)
> ARG_1: Quantity(-2.5056405457707105E119)
> ARG_2: Quantity(1.298014725089379E124)
    at munit.Assertions.fail(Assertions.scala:261)
    at munit.Assertions.fail$(Assertions.scala:255)
    at munit.FunSuite.fail(FunSuite.scala:11)
    at munit.ScalaCheckSuite.$anonfun$propToTry$4(ScalaCheckSuite.scala:104)
    at scala.util.Try$.apply(Try.scala:210)
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:104)
    at munit.ScalaCheckSuite.$anonfun$scalaCheckPropTransform$3(ScalaCheckSuite.scala:46)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:438)
    at munit.Suite$$anon$1.execute(Suite.scala:26)
    at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
    at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
    at scala.concurrent.impl.Promise$DefaultPromise.transform(Promise.scala:128)
    at munit.internal.FutureCompat$ExtensionFuture.transformCompat(FutureCompat.scala:16)
    at munit.ScalaCheckSuite.$anonfun$scalaCheckPropTransform$2(ScalaCheckSuite.scala:48)
    at munit.GenericTest.$anonfun$withBodyMap$1(GenericTest.scala:33)
    at munit.MUnitRunner.$anonfun$runTestBody$1(MUnitRunner.scala:290)
```

**Comment by erikerlandson** [comment]
https://github.com/typelevel/kind-projector/issues/169

**Comment by erikerlandson** [comment]
This looks like it has resolved itself. Not sure what was happening but may have been property testing briefly out of sync with some dep.
